
(function(){
  'use strict';
  var BUILD='v5.16-banco-autoral-1650-hud';
  var AREA_CATALOG=[{"id":"all","label":"Todas as áreas","tag":"Geral","desc":"Sessão misturada com todo o banco autoral."},{"id":"hematology","label":"Hematologia Clínica","tag":"Hemato","desc":"Hemograma, morfologia, anemia, leucemias, hemostasia e interpretação laboratorial."},{"id":"biochemistry","label":"Bioquímica Clínica","tag":"Bioq","desc":"Painéis metabólicos, enzimas, renal, hepático, eletrólitos e interferentes."},{"id":"microbiology","label":"Microbiologia Clínica","tag":"Micro","desc":"Gram, cultura, identificação, antibiograma, micologia, BAAR e CQ."},{"id":"immunology","label":"Imunologia Clínica e Sorologia","tag":"Imuno","desc":"Sorologias, imunoensaios, autoimunidade, janelas diagnósticas e interferentes."},{"id":"parasitology","label":"Parasitologia Clínica","tag":"Parasito","desc":"Protozoários, helmintos, diagnóstico, técnicas parasitológicas e identificação."},{"id":"urinalysis","label":"Urianálise","tag":"Urina","desc":"Físico, químico, sedimento, cilindros, cristais e interferentes."},{"id":"fluids","label":"Líquidos Corporais","tag":"Líquidos","desc":"LCR, pleural, ascítico, sinovial e diferenciais laboratoriais."},{"id":"cytology","label":"Citologia Oncótica","tag":"Cito","desc":"Papanicolau, Bethesda, adequabilidade, agentes e atipias."},{"id":"semen","label":"Espermograma e Reprodução Humana","tag":"Sêmen","desc":"Coleta, motilidade, morfologia, concentração, vitalidade e reprodução humana."},{"id":"quality","label":"Gestão de Qualidade e Fase Pré-Analítica","tag":"Quali","desc":"CQ, Westgard, calibração, rastreabilidade, segurança e fase pré-analítica."},{"id":"forensics","label":"Perícia Criminal","tag":"Perícia","desc":"Cadeia de custódia, vestígios, genética forense, toxicologia e criminalística."}];   var LEVELS=[{id:'all',label:'Todos'},{id:'basico',label:'Básico'},{id:'intermediario',label:'Intermediário'},{id:'avancado',label:'Avançado'}];
  var MODES=[{id:'study',label:'Estudo'},{id:'exam',label:'Prova'}];
  var SIZES=[{id:'5',label:'5'},{id:'10',label:'10'},{id:'20',label:'20'},{id:'50',label:'50'},{id:'100',label:'100'},{id:'all',label:'Todas'}];
  var COMP_GROUPS=[
    {title:'Geral',items:['all']},
    {title:'Reconhecimento',items:['identificacao','criterio_morfologico','diferenciacao']},
    {title:'Raciocínio laboratorial',items:['interpretacao_resultado','correlacao_laboratorial','conduta_tecnica','caso']},
    {title:'Qualidade e erros',items:['armadilha_pre_analitica','armadilha_analitica','controle_qualidade','seguranca_laboratorial','armadilha']}
  ];
  var COMP_LABELS={all:'Todas',identificacao:'Identificação',criterio_morfologico:'Critério morfológico',diferenciacao:'Diferenciação',interpretacao_resultado:'Interpretação de resultado',correlacao_laboratorial:'Correlação laboratorial',conduta_tecnica:'Conduta técnica',caso:'Caso clínico/lab',armadilha_pre_analitica:'Armadilha pré-analítica',armadilha_analitica:'Armadilha analítica',controle_qualidade:'Controle de qualidade',seguranca_laboratorial:'Segurança laboratorial',armadilha:'Armadilha'};
  var pendingCompetency='all';
  var prevHud=(typeof renderHud==='function')?renderHud:null;
  var prevSync=(typeof syncVisualState==='function')?syncVisualState:null;
  function bank(){return window.NYX_QUIZ_BANK_V23||[];}
  function gridEl(){return window.grid||document.getElementById('grid');}
  function keysEl(){return document.querySelector('.keys');}
  function hudEl(){return window.hud||document.getElementById('hud');}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function clone(o){return JSON.parse(JSON.stringify(o));}
  function shuffle(a){var out=(a||[]).slice();for(var i=out.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1));var t=out[i];out[i]=out[j];out[j]=t;}return out;}
  function label(list,id){for(var i=0;i<list.length;i++){if(list[i].id===id)return list[i].label;}return id||'';}
  function compFull(id){return COMP_LABELS[id]||String(id||'Todas').replace(/_/g,' ');}
  function areaInfo(id){for(var i=0;i<AREA_CATALOG.length;i++){if(AREA_CATALOG[i].id===id)return AREA_CATALOG[i];}return {id:id||'all',label:id||'Todas as áreas',tag:'Área',desc:''};}
  function beepSafe(k){try{if(typeof beep==='function')beep(k||'short');}catch(e){}}
  function toastSafe(m){try{if(typeof showToast==='function')showToast(m);}catch(e){try{alert(m);}catch(_e){}}}
  function scrollTop(){try{var k=keysEl();if(k)k.scrollTop=0;}catch(e){} }
  function ensure(){try{window.state=state;}catch(e){} if(!state.training)state.training={};var t=state.training;if(!t.v426){t.v426=true;t.step='area';t.view='menu';t.area=null;t.level='all';t.competency='all';t.mode='study';t.size='10';t.session=[];t.index=0;t.responses={};t.history=[];t.lastHistory=t.lastHistory||[];t.showPlan=false;}if(!t.step)t.step='area';if(!t.view)t.view='menu';if(!t.level)t.level='all';if(!t.competency)t.competency='all';if(!t.mode)t.mode='study';if(!t.size)t.size='10';if(!Array.isArray(t.session))t.session=[];if(!t.responses||typeof t.responses!=='object')t.responses={};if(!Array.isArray(t.history))t.history=[];if(!Array.isArray(t.lastHistory))t.lastHistory=[];return t;}
  function uniqueByConcept(list){var seen={},out=[];for(var i=0;i<list.length;i++){var k=list[i].conceptId||list[i].id||('q'+i);if(seen[k])continue;seen[k]=1;out.push(list[i]);}return out;}
  function normalize(q){var c=clone(q);var opts=Array.isArray(c.options)?c.options.slice():[];var ans=c.answer;if((ans==null||ans==='')&&typeof c.answerIndex==='number')ans=opts[c.answerIndex];if(ans!=null&&opts.indexOf(ans)<0)opts.push(ans);c.answer=ans;c.prompt=c.prompt||c.stem||'';c.explanation=c.explanation||c.why||'';c.shuffledOptions=shuffle(opts);return c;}
  function filtered(area){var t=ensure(), arr=bank().filter(function(q){return (!area||area==='all'||q.area===area)&&(t.level==='all'||q.level===t.level)&&(t.competency==='all'||q.competency===t.competency);});return arr;}
  function limit(list){var t=ensure(), n=t.size==='all'?list.length:Math.min(parseInt(t.size,10)||10,list.length);return list.slice(0,n);}
  function current(){var t=ensure();return t.session[t.index]||null;}
  function responseFor(i){var t=ensure();return (t.responses||{})[String(i)];}
  function score(){var t=ensure(), s=0;Object.keys(t.responses||{}).forEach(function(k){if(t.responses[k]&&t.responses[k].correct)s++;});return s;}
  function percent(a,b){return b?Math.round(a/b*100):0;}
  function buildHistory(){var t=ensure(), out=[];for(var i=0;i<t.session.length;i++){var r=responseFor(i),q=t.session[i];if(r&&q)out.push({area:q.area,areaLabel:q.areaLabel,level:q.level,competency:q.competency,conceptId:q.conceptId,id:q.id,topic:q.topic,prompt:q.prompt||q.stem,selected:r.selected,answer:q.answer,correct:r.correct,explanation:q.explanation||q.why||'',ref:''});}return out;}
  function configText(){var t=ensure();return label(LEVELS,t.level)+' · '+compFull(t.competency)+' · '+label(MODES,t.mode)+' · '+label(SIZES,t.size);}
  function chipRow(list,current,key){var h='<div class="nyxq426-chips">';for(var i=0;i<list.length;i++){var x=list[i];h+='<button class="nyxq426-chip '+(x.id===current?'active':'')+'" type="button" data-q426-action="set-filter" data-q426-key="'+esc(key)+'" data-q426-value="'+esc(x.id)+'">'+esc(x.label)+'</button>';}return h+'</div>';}
  function rootStart(){return '<main class="nyxq426-app"><section class="nyxq426-screen">';}
  function rootEnd(){return '</section></main><section id="nyxq426CompSheet" class="nyxq426-sheet-backdrop" aria-hidden="true"></section>';}
  function renderMenu(){var t=ensure();t.view='menu';var html=rootStart();if(t.step!=='filters')t.step='area';if(t.step==='area'){html+='<section class="nyxq426-step-head"><small>Etapa 1 de 3</small><b>Selecione a área</b><span>Depois você ajusta nível, competência, modo e tamanho.</span><div class="nyxq426-breadcrumb"><span class="on">Área</span><span>›</span><span>Filtros</span><span>›</span><span>Iniciar</span></div></section><section class="nyxq426-area-grid">';for(var i=0;i<AREA_CATALOG.length;i++){var a=AREA_CATALOG[i];var has=a.id==='all'||bank().some(function(q){return q.area===a.id;});if(!has)continue;html+='<button class="nyxq426-area-card '+(t.area===a.id?'active':'')+'" type="button" data-q426-action="select-area" data-q426-area="'+esc(a.id)+'"><small>'+esc(a.tag)+'</small><b>'+esc(a.label)+'</b></button>';}html+='</section><section class="nyxq426-action-row"><button class="nyxq426-btn good" type="button" data-q426-action="quick">Treino rápido</button><button class="nyxq426-btn warn" type="button" data-q426-action="review-stored">Revisar erros</button></section>';}
    else{html+='<section class="nyxq426-step-head"><small>Etapa 2 de 3</small><b>'+esc(areaInfo(t.area).label)+'</b><span>'+esc(configText())+'</span><div class="nyxq426-breadcrumb"><span>Área</span><span>›</span><span class="on">Filtros</span><span>›</span><span>Iniciar</span></div></section>';html+='<section class="nyxq426-card nyxq426-filter-card"><div class="nyxq426-filter-row"><span class="nyxq426-filter-title">Nível</span>'+chipRow(LEVELS,t.level,'level')+'</div><div class="nyxq426-filter-row"><span class="nyxq426-filter-title">Competência</span><button class="nyxq426-comp-button" type="button" data-q426-action="open-comp"><span><b>'+esc(compFull(t.competency))+'</b><span>Toque para alterar</span></span><i>Alterar</i></button></div><div class="nyxq426-filter-row"><span class="nyxq426-filter-title">Modo</span>'+chipRow(MODES,t.mode,'mode')+'</div><div class="nyxq426-filter-row"><span class="nyxq426-filter-title">Sessão</span>'+chipRow(SIZES,t.size,'size')+'</div></section><nav class="nyxq426-start-actions"><button class="nyxq426-btn" type="button" data-q426-action="back-area">Trocar área</button><button class="nyxq426-btn good" type="button" data-q426-action="start">Iniciar</button></nav>';}
    html+=rootEnd();var g=gridEl();if(g){g.className='nyxq426-grid';g.innerHTML=html;bind();}scrollTop();}
  function startSession(area){var t=ensure();var pool=filtered(area);if(!pool.length&&area&&area!=='all')pool=bank().filter(function(q){return q.area===area;});if(!pool.length)pool=bank().slice();if(!pool.length){toastSafe('Nenhuma questão encontrada.');return;}t.area=area||t.area||'all';t.session=limit(uniqueByConcept(shuffle(pool))).map(normalize);t.index=0;t.responses={};t.history=[];t.view='quiz';t.showPlan=false;beepSafe('short');renderQuestion();}
  function answerOption(value){var t=ensure(), q=current();if(!q)return;var key=String(t.index);if(t.responses[key])return;var correct=value===q.answer;t.responses[key]={selected:value,correct:correct};beepSafe(correct?'short':'long');renderQuestion(false);}
  function renderQuestion(){var t=ensure(), q=current();if(!q)return renderMenu();var total=t.session.length,idx=t.index+1,r=responseFor(t.index),pct=Math.round(idx/Math.max(1,total)*100);var html=rootStart();html+='<section class="nyxq426-progress"><div class="nyxq426-progress-row"><span>'+esc(areaInfo(q.area).label)+' · '+esc(label(LEVELS,q.level))+'</span><span>'+idx+'/'+total+'</span></div><div class="nyxq426-bar"><i style="width:'+pct+'%"></i></div></section><article class="nyxq426-question-card"><div class="nyxq426-meta"><span class="nyxq426-pill">'+esc(compFull(q.competency))+'</span><span class="nyxq426-pill">'+esc(q.topic||'Questão')+'</span></div><div class="nyxq426-prompt">'+esc(q.prompt||q.stem)+'</div>'+(q.learningGoal?'<div class="nyxq426-learning-goal">'+esc(q.learningGoal)+'</div>':'')+'<div class="nyxq426-options">';var opts=q.shuffledOptions||q.options||[];for(var i=0;i<opts.length;i++){var op=opts[i],cls='';if(r){if(op===q.answer)cls=' correct';else if(op===r.selected)cls=' wrong';}html+='<button class="nyxq426-option'+cls+'" type="button" '+(r?'disabled':'')+' data-q426-action="answer" data-q426-value="'+esc(op)+'">'+esc(op)+'</button>';}html+='</div>';if(r&&(t.mode==='study'||!r.correct)){html+='<div class="nyxq426-explain"><b>'+(r.correct?'Correto.':'Resposta correta: '+esc(q.answer))+'</b><br>'+esc(q.explanation||q.why||'Sem explicação cadastrada.')+(q.ref?'<small>Base técnica: '+esc(q.ref)+'</small>':'')+'</div>';}html+='</article><nav class="nyxq426-bottom-nav"><button class="nyxq426-btn" type="button" data-q426-action="prev">Voltar</button><span class="nyxq426-counter">'+idx+' / '+total+'</span><button class="nyxq426-btn good" type="button" data-q426-action="next">'+(idx===total?'Finalizar':'Próxima')+'</button></nav>';html+=rootEnd();var g=gridEl();if(g){g.className='nyxq426-grid';g.innerHTML=html;bind();}scrollTop();}
  function nextQuestion(){var t=ensure();if(!responseFor(t.index)){toastSafe('Responda antes de avançar.');return;}if(t.index>=t.session.length-1){t.history=buildHistory();t.lastHistory=t.history.slice();t.view='report';renderReport();return;}t.index++;renderQuestion();}
  function prevQuestion(){var t=ensure();if(t.index>0){t.index--;renderQuestion();}}
  function weakList(hist){var buckets={};hist.forEach(function(h){['area','level','competency'].forEach(function(k){var id=h[k]||'all',key=k+':'+id;if(!buckets[key])buckets[key]={k:k,id:id,total:0,score:0};buckets[key].total++;if(h.correct)buckets[key].score++;});});var out=[];Object.keys(buckets).forEach(function(key){var b=buckets[key],p=percent(b.score,b.total);if(b.total>=2&&p<70){var name=b.k==='area'?areaInfo(b.id).label:b.k==='level'?label(LEVELS,b.id):compFull(b.id);out.push(name+' ('+p+'%)');}});return out;}
  function studyPlan(hist){var weak=weakList(hist), days=['Dia 1: revisar fundamentos dos temas com menor acurácia.','Dia 2: refazer as questões erradas sem consulta.','Dia 3: revisar critérios morfológicos e armadilhas pré-analíticas.','Dia 4: treinar questões por competência fraca.','Dia 5: simulado curto de 20 questões.','Dia 6: revisar explicações e POP local.','Dia 7: novo simulado e comparação com o resultado anterior.'];return {weak:weak,days:days};}
  function renderStudyPlan(){var hist=ensure().history.length?ensure().history:buildHistory(),p=studyPlan(hist),html='<section class="nyxq426-study-plan"><article class="nyxq426-report-card"><h2>Plano de estudo</h2><p>Gerado automaticamente a partir dos erros, acertos e competências da sessão.</p></article><article class="nyxq426-plan-block"><h3>Prioridades</h3>'+(p.weak.length?'<div class="nyxq426-plan-priority">'+p.weak.map(function(x){return '<span class="nyxq426-plan-pill">'+esc(x)+'</span>';}).join('')+'</div>':'<p>Nenhum ponto crítico detectado nesta sessão.</p>')+'</article><article class="nyxq426-plan-block"><h3>Roteiro de 7 dias</h3><ul>'+p.days.map(function(d){return '<li>'+esc(d)+'</li>';}).join('')+'</ul></article></section>';return html;}
  function renderReport(){var t=ensure();var hist=buildHistory();if(hist.length)t.history=hist;if(!t.history.length&&t.lastHistory.length)t.history=t.lastHistory.slice();hist=t.history;var total=hist.length,sc=hist.filter(function(h){return h.correct;}).length,acc=percent(sc,total),weak=weakList(hist);var html=rootStart();html+='<article class="nyxq426-report-card"><h2>Relatório do Quiz</h2><p>Resumo da sessão e pontos para revisar.</p><div class="nyxq426-summary-grid"><div class="nyxq426-stat"><small>Acertos</small><b>'+sc+'</b></div><div class="nyxq426-stat"><small>Total</small><b>'+total+'</b></div><div class="nyxq426-stat"><small>Acurácia</small><b>'+acc+'%</b></div></div></article>';if(weak.length)html+='<article class="nyxq426-report-card"><b>Pontos para revisar</b><span>'+weak.map(esc).join('<br>')+'</span></article>';html+='<nav class="nyxq426-bottom-nav"><button class="nyxq426-btn" type="button" data-q426-action="menu">Menu</button><span class="nyxq426-counter">Relatório</span><button class="nyxq426-btn good" type="button" data-q426-action="review-stored">Erros</button></nav><section class="nyxq426-report-actions"><button class="nyxq426-btn" type="button" data-q426-action="copy-report">Copiar relatório</button><button class="nyxq426-btn warn" type="button" data-q426-action="toggle-plan">Plano de estudo</button></section>';if(t.showPlan)html+=renderStudyPlan();html+='<section class="nyxq426-report-list">';for(var i=0;i<hist.length;i++){var h=hist[i];html+='<div class="nyxq426-report-item"><b class="'+(h.correct?'nyxq426-ok':'nyxq426-bad')+'">'+(i+1)+'. '+(h.correct?'ACERTO':'ERRO')+' — '+esc(h.topic||areaInfo(h.area).label)+'</b><span>'+esc(h.prompt)+'</span><span>Sua resposta: '+esc(h.selected)+'</span><span>Correta: '+esc(h.answer)+'</span>'+(h.explanation?'<span>'+esc(h.explanation)+'</span>':'')+'</div>';}html+='</section>'+rootEnd();var g=gridEl();if(g){g.className='nyxq426-grid';g.innerHTML=html;bind();}scrollTop();}
  function reviewErrors(){var t=ensure(), source=t.history.length?t.history:(t.lastHistory||[]), concepts={};source.forEach(function(h){if(!h.correct)concepts[h.conceptId]=1;});var pool=bank().filter(function(q){return concepts[q.conceptId];});if(!pool.length){toastSafe('Sem erros para revisar.');return;}t.area='all';t.mode='study';t.session=pool.map(normalize);t.index=0;t.responses={};t.history=[];t.view='quiz';renderQuestion();}
  function reportText(){var t=ensure(), hist=t.history.length?t.history:buildHistory(),sc=hist.filter(function(h){return h.correct;}).length;var lines=['NYX Cell Counter Pro v5.16 — Relatório do Banco Autoral','Configuração: '+configText(),'Resultado: '+sc+'/'+hist.length,''];hist.forEach(function(h,i){lines.push((i+1)+'. '+(h.correct?'ACERTO':'ERRO')+' — '+areaInfo(h.area).label+' / '+label(LEVELS,h.level));lines.push('Pergunta: '+h.prompt);lines.push('Sua resposta: '+h.selected);lines.push('Correta: '+h.answer);if(h.explanation)lines.push('Explicação: '+h.explanation);lines.push('');});return lines.join('\n');}
  function copyReport(){var txt=reportText();function ok(){toastSafe('Relatório copiado.');}function fallback(){var ta=document.createElement('textarea');ta.value=txt;document.body.appendChild(ta);ta.select();try{document.execCommand('copy');ok();}catch(e){toastSafe('Não foi possível copiar.');}document.body.removeChild(ta);}if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(txt).then(ok).catch(fallback);else fallback();}
  function copyStudyPlan(){var text=document.querySelector('.nyxq426-study-plan')?document.querySelector('.nyxq426-study-plan').innerText:'Plano de estudo indisponível.';if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(text).then(function(){toastSafe('Plano copiado.');});}
  function openSheet(){var t=ensure();pendingCompetency=t.competency||'all';var sheet=document.getElementById('nyxq426CompSheet');if(!sheet)return;var html='<section class="nyxq426-sheet"><div class="nyxq426-sheet-head"><div><small>Competência</small><b>Escolha o foco</b><span>Filtra o banco por habilidade avaliada.</span></div><button class="nyxq426-sheet-close" type="button" data-q426-action="close-sheet">×</button></div><div class="nyxq426-sheet-body">';COMP_GROUPS.forEach(function(g){html+='<div class="nyxq426-comp-group"><div class="nyxq426-comp-title">'+esc(g.title)+'</div><div class="nyxq426-comp-grid">';g.items.forEach(function(id){html+='<button class="nyxq426-comp-option '+(pendingCompetency===id?'active':'')+'" type="button" data-q426-action="choose-comp" data-q426-comp="'+esc(id)+'">'+esc(compFull(id))+'</button>';});html+='</div></div>';});html+='</div><div class="nyxq426-sheet-actions"><button class="nyxq426-btn" type="button" data-q426-action="clear-comp">Limpar</button><button class="nyxq426-btn good" type="button" data-q426-action="apply-comp">Aplicar</button></div></section>';sheet.innerHTML=html;sheet.classList.add('show');sheet.setAttribute('aria-hidden','false');}
  function closeSheet(){var sheet=document.getElementById('nyxq426CompSheet');if(sheet){sheet.classList.remove('show');sheet.setAttribute('aria-hidden','true');sheet.innerHTML='';}}
  function resetTraining426(){var t=ensure();t.step='area';t.view='menu';t.area=null;t.level='all';t.competency='all';t.mode='study';t.size='10';t.session=[];t.index=0;t.responses={};t.history=[];t.showPlan=false;renderMenu();}
  function bind(){var g=gridEl();if(!g)return;g.onclick=function(e){var el=e.target.closest('[data-q426-action]');if(!el)return;var a=el.getAttribute('data-q426-action'),t=ensure();if(a==='select-area'){t.area=el.getAttribute('data-q426-area');t.step='filters';beepSafe('short');renderMenu();}else if(a==='quick'){t.area='all';t.level='all';t.competency='all';t.mode='study';t.size='10';startSession('all');}else if(a==='review-stored'){reviewErrors();}else if(a==='back-area'){t.step='area';beepSafe('short');renderMenu();}else if(a==='start'){startSession(t.area||'all');}else if(a==='set-filter'){t[el.getAttribute('data-q426-key')]=el.getAttribute('data-q426-value');beepSafe('short');renderMenu();}else if(a==='open-comp'){openSheet();}else if(a==='close-sheet'){closeSheet();}else if(a==='clear-comp'){pendingCompetency='all';openSheet();}else if(a==='choose-comp'){pendingCompetency=el.getAttribute('data-q426-comp');openSheet();}else if(a==='apply-comp'){t.competency=pendingCompetency;closeSheet();renderMenu();}else if(a==='answer'){answerOption(el.getAttribute('data-q426-value'));}else if(a==='next'){nextQuestion();}else if(a==='prev'){prevQuestion();}else if(a==='menu'){t.step='area';t.view='menu';renderMenu();}else if(a==='toggle-plan'){t.showPlan=!t.showPlan;renderReport();}else if(a==='copy-report'){copyReport();}else if(a==='copy-plan'){copyStudyPlan();}};var sheet=document.getElementById('nyxq426CompSheet');if(sheet){sheet.onclick=function(e){if(e.target===sheet)closeSheet();};}}
  function renderTraining426(){ensure();try{document.body.classList.add('nyx-quiz-standalone-426');document.body.classList.remove('nyx-quiz-native-425');document.body.setAttribute('data-stable-build',BUILD);}catch(e){}var t=ensure();if(t.view==='quiz')renderQuestion();else if(t.view==='report')renderReport();else renderMenu();}
  try{renderHud=function(){
    if(state&&state.mode==='training'){
      var h=hudEl();
      try{document.body.classList.add('nyx-quiz-standalone-426');document.body.classList.remove('nyx-quiz-native-425');document.body.setAttribute('data-stable-build',BUILD+'-hud');}catch(e){}
      if(h){
        var t=ensure();
        var inSession=t.view==='quiz'&&t.session&&t.session.length;
        var total=inSession?t.session.length:0;
        var idx=inSession?(t.index||0)+1:0;
        var answeredCount=t.responses?Object.keys(t.responses).length:0;
        var score=0;
        if(t.responses){Object.keys(t.responses).forEach(function(k){if(t.responses[k]&&t.responses[k].correct)score++;});}
        var pct=inSession?Math.round(idx/Math.max(1,total)*100):(t.view==='report'?100:0);
        var areaText=inSession?areaInfo((current()||{}).area||t.area).label:(t.view==='report'?'Relatório':(t.step==='filters'?areaInfo(t.area).label:'Banco autoral'));
        var levelText=inSession?label(LEVELS,(current()||{}).level||t.level):'1.650 questões';
        var status=inSession?('Questão '+idx+'/'+total+' · '+areaText+' · '+levelText):(t.view==='report'?('Resultado '+score+'/'+(t.history?t.history.length:answeredCount)):'Escolha área, nível, competência e modo');
        var nextLabel=inSession?(idx===total?'Finalizar':'Próx.'):(t.view==='report'?'Áreas':(t.step==='filters'?'Iniciar':'Rápido'));
        h.innerHTML='<section class="readout-row clean-hud-readout nyxq426-hud-readout"><div class="readout"><span class="mode">NYX Quiz</span><h1 class="total">'+score+'<small>/'+answeredCount+'</small></h1></div><div class="progress-wrap"><div class="progress"><i style="width:'+pct+'%"></i></div><div class="status">'+esc(status)+'</div></div></section><section class="control-row clean-control-row training-actions nyxq426-hud-actions"><button class="btn" id="homeBtn" type="button">Início</button><button class="btn" id="trainingMenuHudBtn" type="button">Áreas</button><button class="btn good" id="trainingHudNextBtn" type="button">'+esc(nextLabel)+'</button><button class="btn" id="trainingReportHudBtn" type="button">Relat.</button><button class="btn danger" id="trainingResetBtn" type="button">Zerar</button></section>';
        var home=document.getElementById('homeBtn'); if(home)home.onclick=function(){try{openHome();}catch(e){}};
        var menu=document.getElementById('trainingMenuHudBtn'); if(menu)menu.onclick=function(){t.step='area';t.view='menu';renderMenu();};
        var next=document.getElementById('trainingHudNextBtn'); if(next)next.onclick=function(){if(t.view==='quiz')nextQuestion();else if(t.view==='report'){t.step='area';t.view='menu';renderMenu();}else{if(t.step==='filters')startSession(t.area||'all');else startSession('all');}};
        var rep=document.getElementById('trainingReportHudBtn'); if(rep)rep.onclick=function(){var hist=buildHistory();if(hist.length)t.history=hist;if((t.history&&t.history.length)||(t.lastHistory&&t.lastHistory.length)){t.view='report';renderReport();}else toastSafe('Sem sessão para relatório.');};
        var reset=document.getElementById('trainingResetBtn'); if(reset)reset.onclick=function(){resetTraining426();};
      }
      return;
    }
    try{document.body.classList.remove('nyx-quiz-standalone-426');}catch(e){}
    if(prevHud)return prevHud();
  };window.renderHud=renderHud;}catch(e){}
  try{syncVisualState=function(){if(prevSync)prevSync();try{var on=state&&state.mode==='training';document.body.classList.toggle('nyx-quiz-standalone-426',!!on);if(on)document.body.classList.remove('nyx-quiz-native-425');}catch(e){}};window.syncVisualState=syncVisualState;}catch(e){}
  try{renderTrainingModule=renderTraining426;window.renderTrainingModule=renderTraining426;}catch(e){}
  try{resetTraining=resetTraining426;window.resetTraining=resetTraining426;}catch(e){}
  try{answerTraining=answerOption;window.answerTraining=answerOption;}catch(e){}
  try{nextTrainingCase=nextQuestion;window.nextTrainingCase=nextQuestion;}catch(e){}
  function polishHome(){try{var c=document.querySelector('.home-option.training');if(!c)return;var small=c.querySelector('small'),b=c.querySelector('b'),span=c.querySelector('span');if(small)small.textContent='Treino';if(b)b.textContent='Banco autoral';if(span)span.textContent='1.650 questões autorais integradas ao app.';}catch(e){}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',polishHome);else polishHome();window.addEventListener('load',polishHome);
})();

